version: 0.1.{build}
skip_tags: true
image: Visual Studio 2015
clone_depth: 1
assembly_info:
  patch: true
  file: '**\AssemblyInfo.*'
  assembly_version: '{version}'
  assembly_file_version: '{version}'
  assembly_informational_version: '{version}-alpha'
nuget:
  project_feed: true
  disable_publish_on_pr: true
build_script:
- ps: .\build.ps1
test: off
